package com.elex.chatservice.model;

public class LanguageKeys
{
	public static final String	TIP_JOIN_ALLIANCE						= "E100068";			// 您未加入联盟，暂时无法使用联盟聊天频道
	public static final String	MENU_JOIN								= "115020";				// 加入
	public static final String	MENU_BAN								= "105207";				// 禁言
	public static final String	MENU_UNBAN								= "105209";				// 已禁言
	public static final String	TIP_BAN									= "105210";				// 是否禁言：{0}？
	public static final String	BTN_COUNTRY								= "105300";				// 国家
	public static final String	BTN_SEND								= "105302";				// 发送
	public static final String	MENU_COPY								= "105304";				// 复制
	public static final String	TIP_SENDMSG_WARN						= "105307";				// 您发布的聊天消息过于频繁，请稍等！
	public static final String	MENU_SENDMSG							= "105308";				// 发送邮件
	public static final String	MENU_VIEWPLAYER							= "105309";				// 查看玩家
	public static final String	MENU_SHIELD								= "105312";				// 屏蔽
	public static final String	TIP_SHIELD_PLAYER						= "105313";				// 是否要屏蔽{0}，屏蔽后你将不会收到该玩家的任何聊天信息和邮件，但是你可以通过设置来解除对该玩家的屏蔽。
	public static final String	MENU_UNSHIELD							= "105315";				// 解除屏蔽

	public static final String	TITLE_CHAT								= "105316";				// 聊天
	public static final String	TIP_TRANSLATED_BY						= "105321";				// 由{0}翻译
	public static final String	MENU_ORIGINALLAN						= "105322";				// 原文
	public static final String	TIP_DOWNLOADMORE						= "105502";				// 下滑加载更多
	public static final String	BTN_ALLIANCE							= "105602";				// 联盟
	public static final String	MENU_INVITE								= "108584";				// 邀请加入联盟
	public static final String	MENU_SHIELD_PLAYERCHAT					= "115922";				// 屏蔽该玩家留言

	public static final String	MENU_SHIELD_ALLIANCECHAT				= "115923";				// 屏蔽该联盟留言
	public static final String	TIP_SHIELD_PLAYER_CHATTO_ALLIANCE		= "115925";				// 是否要屏蔽{0}，屏蔽后该玩家将无法对您的联盟进行留言，但是你可以通过联盟管理来解除对该玩家的屏蔽。
	public static final String	TIP_SHIELD_ALLIANCE_CHATTO_ALLIANCE		= "115926";				// 是否要屏蔽{0}，屏蔽后该联盟将无法对您的联盟进行留言，但是你可以通过联盟管理来解除对该联盟的屏蔽。
	public static final String	TITLE_ALLIANCEMSG						= "115929";				// 联盟留言
	public static final String	TIP_SYSTEM								= "115181";				// 系统
	public static final String	TIP_INVITE								= "115182";				// 我邀请了{0}加入我们的联盟，希望他能和我们一起并肩作战。
	public static final String	MENU_BATTLEREPORT						= "115281";				// 查看战报
	public static final String	TIP_BATTLEREPORT						= "115282";				// 抱歉，该战报已无法查看

	public static final String	TIP_ADDALLIANCE_REWARD					= "115168";				// 立即加入联盟获得金币
	public static final String	TIP_ADDALLIANCE_COIN					= "115169";				// {0}金币
	public static final String	TIP_ADDALLIANCE_REWARD_SENDBYMAIL		= "115170";				// 通过邮件发送

	public static final String	MENU_TRANSLATE							= "105326";				// 翻译
	public static final String	TIP_PULLDOWN							= "105327";				// 下拉可加载更多
	public static final String	TIP_NOPULLDOWN							= "105328";				// 松开载入更多

	public static final String	FLYHINT_DOWN_MIN						= "105324";				// 服务器即将在{0}分后停机更新
	public static final String	FLYHINT_DOWN_SECOND						= "105325";				// 服务器即将在{0}秒后停机更新

	public static final String	BTN_JOIN_NOW							= "115068";				// 立即加入

	public static final String	BTN_CONFIRM								= "confirm";			// 确定
	public static final String	BTN_CANCEL								= "cancel_btn_label";	// 取消
	public static final String	TIP_LOADING								= "114110";				// 加载中
	public static final String	TIP_REFRESH								= "104932";				// 刷新
	public static final String	TIP_ALLIANCE							= "105564";				// 全体联盟成员
	public static final String	TITLE_MAIL								= "101205";				// 邮件
	public static final String	TITLE_FORUM								= "105329";				// 论坛
	public static final String	MENU_DETECTREPORT						= "105522";				// 侦察战报
	public static final String	TIP_TIME								= "105591";				// 小时
	public static final String	TIP_RESEND								= "105330";				// 是否重发此消息
	public static final String	TIP_USEITEM								= "105332";				// 发送王国公告将消耗1个//
																								// {0}！
	public static final String	TIP_HORN								= "104371";				// 号角
	public static final String	TIP_ITEM_NOT_ENOUGH						= "105333";				// 领主大人，您的{0}不足，花费一些金币即可发送王国公告！
	public static final String	TIP_CORN_NOT_ENOUGH						= "104912";				// 领主大人，您的金币不足，赶快去购买一些吧！
	public static final String	TIP_HORN_TEXT							= "105331";				// 公告
	public static final String	TITLE_RANK1								= "115100";				// 联盟阶级1
	public static final String	TITLE_RANK2								= "115101";				// 联盟阶级2
	public static final String	TITLE_RANK3								= "115102";				// 联盟阶级3
	public static final String	TITLE_RANK4								= "115103";				// 联盟阶级4
	public static final String	TITLE_RANK5								= "115104";				// 联盟阶级5
	public static final String	VIP_INFO								= "103001";				// VIP{0}
	public static final String	SVIP_INFO								= "103076";				// SVIP{0}
	public static final String	TIP_CHATROOM_KICK						= "105348";				// 是否将{0}从群组中移除?
	public static final String	TIP_CHATROOM_INVITE						= "105349";				// 是否将{0}加入群组?
	public static final String	TIP_CHATROOM_QUIT						= "105350";				// 是否确认退出群组?
	public static final String	TIP_CHATROOM_MODIFYNAME					= "105351";				// 是否将群组改名为{0}？
	public static final String	NEW_MESSAGE_ALERT						= "105352";				// {0}条新消息
	public static final String	TIP_NEW_MESSAGE_BELOW					= "105353";				// 以下为新消息
	public static final String	TITLE_CHATROOM							= "105354";				// 多人聊天
	public static final String	TIP_CHATROOM_CREATER					= "105355";				// 创建者
	public static final String	BTN_QUIT_CHATROOM						= "105344";				// 退出群组
	public static final String	TIP_MODIFY_CHATROOM_NAME				= "119004";				// 变更名称
	public static final String	BTN_SEARCH								= "113907";				// 搜索
	public static final String	TIP_SELECTED_MEMBER						= "105356";				// 已加入
	public static final String	TIP_SEARCH_RESULT						= "105357";				// 搜索结果
	public static final String	TIP_N_NEW_MESSAGE_BELOW					= "105369";				// 以下是最近{0}条新消息
	public static final String	MAIL_TABNAME_FIGHT						= "105519";				// 战斗报告
	public static final String	MAIL_TABNAME_DRAGON_TOWER				= "169094";				// 龙塔战报
	public static final String	MAIL_TABNAME_DRAGON_PVE					= "164855";				// PVE战报
	public static final String	MAIL_TABNAME_STUDIO						= "103731";				// 列王的纷争游戏工作室
	public static final String	MAIL_TABNAME_NOTICE						= "105569";				// 公告
	public static final String	MAIL_TABNAME_INVITE						= "103738";				// 邀请函
	public static final String	MAIL_TABNAME_QUITALLIANCE				= "103783";				// 退盟通知
	public static final String	MAIL_TABNAME_ACTIVITYREPORT				= "133053";				// 活动战报
	public static final String	MAIL_TABNAME_ATKSUCESS					= "115337";				// 攻击联盟堡垒胜利
	public static final String	MAIL_TABNAME_ATKFAIL					= "115338";				// 攻击联盟堡垒失败
	public static final String	MAIL_TABNAME_DEFSUCESS					= "115339";				// 防守联盟堡垒胜利
	public static final String	MAIL_TABNAME_DEFFAIL					= "115340";				// 防守联盟堡垒失败
	public static final String	MAIL_TABNAME_ATKBANNERSUCCESS			= "115540";				// 攻击国旗胜利
	public static final String	MAIL_TABNAME_ATKBANNERFAILED			= "115541";				// 攻击国旗失败
	public static final String	MAIL_TABNAME_DEFBANNERSUCCESS			= "115542";				// 防守国旗胜利
	public static final String	MAIL_TABNAME_DEFBANNERFAILED			= "115543";				// 防守国旗失败
	public static final String	TIP_YOU									= "105347";				// 你
	public static final String	MAIL_TABNAME_MOD						= "132000";				// 联系MOD
	public static final String	MAIL_TABNAME_WORLDEXPLORE				= "108675";				// 城堡遗迹探险报告
	public static final String	TIME_DAY								= "105592";				// 天
	public static final String	TIME_HOUR								= "105591";				// 小时
	public static final String	TIME_MIN								= "105590";				// 分钟
	public static final String	TIME_BEFORE								= "105593";				// 之前
	public static final String	MAIL_TITLE_ATTACK						= "105547";				// {0}攻击{1}
	public static final String	MAIL_TITLE_MYARMY						= "102187";				// 我的部队
	public static final String	MAIL_TITLE_MYCASTLE						= "108678";				// 我的城堡
	public static final String	NPC_NAME								= "3000002";			// 阿加莎
	public static final String	MAIL_TITLE_CASTLEMOVE					= "105734";				// 您的城堡已经被迫迁走！
	public static final String	MAIL_CONTENT_CASTLEMOVE					= "105735";				// 由于您长时间未登录，您的城堡被强制迁城到其他地点！
	public static final String	MAIL_BATTLE_TITLE						= "138067";				// 远古战场关闭
	public static final String	MAIL_BATTLE_INFO						= "138068";				// 尊敬的领主大人:\n
																								// 远古战场已经关闭，有人壮志成城而来，满载荣誉而归；有人心怀理想踏入这片战场，最后遗憾而归。\n\n
																								// 您的王国排名{0}\n\n本次活动王国前三名为:\n
																								// 第一名{1}\n
																								// 第二名{2}\n
																								// 第三名{3}
	public static final String	MAIL_DELETE_COMFIRM						= "105570";				// 您真的要删除该邮件吗?
	public static final String	MAIL_CLEAR_CHATROOM_COMFIRM				= "105373";				// 您真的要清空聊天室消息吗?
	public static final String	MAIL_DELETE_THESE_COMFIRM				= "105374";				// 您真的要删除这些邮件吗?
	public static final String	MAIL_DELETE_NOTIFY_REWARD				= "105512";				// 请领取奖励后再删除邮件！
	public static final String	MAIL_NOMORE_DELETE						= "105599";				// 没有邮件可以删除
	public static final String	DELETE									= "108523";				// 删除
	public static final String	MAIL_DELETE_NOTIFY_LOCK					= "4100013";			// 邮件已锁定，请解锁后再删除！
	public static final String	MAIL_DELETE_NOTIFY_REWARD_OR_LOCK		= "4100014";			// 邮件中存在未领奖励或者锁定的邮件，这些邮件已为您保留
	public static final String	MAIL_NEWPLAYER_MOVECASTAL				= "114010";				// 新手迁城
	public static final String	MAIL_TITLE_GIFT							= "101007";				// 来自{0}的礼物
	public static final String	MAIL_INVITE_MOVECASTAL					= "115295";				// 迁城邀请
	public static final String	MAIL_ALLIANCE_APPLY						= "114012";				// 入盟申请
	public static final String	MAIL_ENEMY_KILL							= "105718";				// 击杀敌军活动
	public static final String	MAIL_ALLIANCE_REWARD					= "133017";				// 联盟积分奖励
	public static final String	MAIL_TITLE_WOUNDED						= "105550";				// 收治伤兵
	public static final String	MAIL_OCCUPY_PALACE						= "105710";				// 占领宫殿
	public static final String	MAIL_OCCUPY_CATAPULT					= "105711";				// 占领投石机
	public static final String	MAIL_OCCUPY_SUCESS						= "105537";				// 占领成功！
	public static final String	MAIL_OCCUPY_PALACE_SUCESS				= "105712";				// 你成功占领了宫殿
	public static final String	MAIL_OCCUPY_CATAPULT_SUCESS				= "105713";				// 你成功占领了投石机
	public static final String	MAIL_OCCUPY_POINT						= "105538";				// 您成功占领了{0}（X：{1}
																								// Y：{2}）
	public static final String	MAIL_DETECT_PALACE						= "105708";				// 侦查宫殿成功！
	public static final String	MAIL_DETECT_CATAPULT					= "105709";				// 侦查投石机成功！
	public static final String	MAIL_DETECT_CASTLE_SUCESS				= "115356";				// 侦查联盟堡垒成功！
	public static final String	MAIL_DETECT_BANNER_SUCESS				= "115539";				// 侦查国旗成功！
	public static final String	MAIL_DETECT_SUCESS						= "105527";				// 侦查成功！
	public static final String	MAIL_ALLIANCE_CASTLE					= "115312";				// 联盟堡垒{0}
	public static final String	MAIL_BANNER								= "115534";				// 国旗

	public static final String	MAIL_DETECT_INFO						= "114101";				// 已侦查到{0}的信息
	public static final String	BATTLE_FIELD							= "138039";				// 战场
	public static final String	MAIL_TITLE_RESOURCEHELP					= "114121";				// 资源帮助报告
	public static final String	MAIL_TITLE_WORLDBOSS					= "137451";				// 挑战世界BOSS战报
	public static final String	MAIL_TITLE_ALLIANCEBOSS					= "2910538";				// 挑战世界BOSS战报
	public static final String	MAIL_CONTENT_WORLDBOSS					= "137450";				// {0}集结的队伍挑战了守护者
	public static final String	MAIL_CONTENT_ALLIANCEBOSS				= "137450";				// {0}集结的队伍挑战了守护者
	public static final String	MAIL_NAME_RESOURCE						= "105516";				// 资源采集报告
	public static final String	MAIL_NAME_MESSAGE						= "105384";				// 信息
	public static final String	MAIL_NAME_DRIFTING_BOTTLE				= "111889";				// 漂流瓶

	public static final String	TIP_EQUIP_SHARE							= "111660";				// 我刚刚在铁匠铺在成功的锻造出了{0}
	public static final String	MAIL_TITLE_EVENT						= "105383";				// 活动
	public static final String	MENU_REPORT_HEADIMG						= "105777";				// 举报头像
	public static final String	WRITE_MAIL_CONTENT						= "105504";				// 内容
	public static final String	WRITE_MAIL_RECIEVER						= "105505";				// 收件人
	public static final String	TIP_REPORT_HEADIMG						= "105778";				// 是否要举报{0}的自定义头像？
	public static final String	TIP_REPORT_HEADIMG_SUCCESS				= "105781";				// 举报头像成功
	public static final String	TIP_HEADIMG_REPORTED					= "105782";				// 您已经举报过该领主头像了
	public static final String	TIP_NO_MAIL								= "105385";				// 信箱里一封信都没有，下次再来看看吧
	public static final String	MENU_VIEW_EQUIPMENT						= "111665";				// 查看装备
	public static final String	TIP_MAIL_NOREWARD						= "105387";				// 领主大人，您的邮件中已经没有奖励可领!
	public static final String	TIP_REWARD_THESE_MAIL					= "105388";				// 您真的要全部领取这些邮件的奖励吗?
	public static final String	MENU_REPORT_PLAYER_CHAT					= "105392";				// 举报消息
	public static final String	TIP_CONTETN_REPORTED					= "105395";				// 您已经举报过该条信息了
	public static final String	TIP_REPORT_CONTENT_SUCCESS				= "105394";				// 您的举报已经提交，感谢您为提升游戏内环境作出的贡献
	public static final String	TIP_REPORT_CONTENT						= "105393";				// 确认举报该条消息？

	public static final String	MENU_REPORT_CHAT_TRANSLATION			= "105396";				// 翻译不好
	public static final String	TIP_REPORT_TRASNALTION					= "105397";				// 确认提交此条消息给翻译改进系统吗
	public static final String	TIP_REPORT_TRANSLATION_SUCCESS			= "105398";				// 翻译改进条目已经记录，感谢您为改善游戏内翻译作出的贡献
	public static final String	TIP_TRANSLATION_REPORTED				= "105399";				// 您已经提交过该消息了，请勿重复提交
	public static final String	TIP_TRANSLATION_REPORTED_CHECKBOX_TEXT	= "132488";				// 不再提示

	public static final String	TITLE_TRANSLATION_OPTIMIZATION			= "105400";				// 翻译纠错
	public static final String	TIP_REPORT_CONTENT_INTERVAL				= "132117";				// 您举报信息过于频繁，请稍后再试
	public static final String	BTN_FRIEND								= "132106";				// 好友
	public static final String	MENU_MARKASREAD							= "132120";				// 标记已读
	public static final String	TITLE_FRIEND_LIST						= "132103";				// 好友列表
	public static final String	MENU_SAY_HELLO							= "132121";				// 打招呼
	public static final String	MENU_VIEW_RALLY_INFO					= "132119";				// 查看集结消息
	public static final String	SAY_HELLO1								= "132122";				// 欢迎欢迎
	public static final String	SAY_HELLO2								= "132123";				// 欢迎{1}加入{0}
	public static final String	SAY_HELLO3								= "132124";				// {0}欢迎你的加入，咱们一起好好玩
	public static final String	SAY_HELLO4								= "132125";				// 欢迎加入，先做个自我介绍吧
	public static final String	MENU_VIEW								= "115018";				// 查看
	public static final String	TIP_ALLIANCE_TASK_SHARE_1				= "134054";				// {0}刚刚发布了联盟任务{1}，请大家前往协助
	public static final String	TIP_ALLIANCE_TASK_SHARE_2				= "134055";				// {0}刚刚发布的联盟任务{1}已经被{2}接取
	public static final String	MENU_VIEW_TASK							= "134058";				// 接取任务
	public static final String	TIP_CHAT_RESTRICT						= "132130";				// 让世界见到一个有名有姓的人！请先给自己起个名字再来世界频道发言吧。
	public static final String	BTN_CHANGE_NAME							= "101263";				// 改名
	public static final String	TITLE_JOIN_ALLIANCE						= "133006";				// 加入联盟
	public static final String	TIP_JOIN_ALLIANCE_TITLE					= "115572";				// 首次加入联盟，可以获得{0}金币奖励！
	public static final String	TIP_FIRST_JOIN_ALLIANCE_1				= "115573";				// 盟友可以帮助你升级建筑
	public static final String	TIP_FIRST_JOIN_ALLIANCE_2				= "115574";				// 研究联盟科技，获得强大增益
	public static final String	TIP_FIRST_JOIN_ALLIANCE_3				= "115575";				// 建造联盟堡垒，获得联盟领地
	public static final String	TIP_FIRST_JOIN_ALLIANCE_4				= "115576";				// 参与联盟战争，多人集结进攻
	public static final String	TIP_RED_PACKAGE_CONTENT					= "104974";				// 点击领取
	public static final String	TIP_RED_PACKAGE_CONTENT_2				= "104986";				// 点击查看
	public static final String	TIP_RED_PACKAGE_TITLE					= "104973";				// 各位朋友快来抢{0}啦
	public static final String	ITEM_RED_PACKAGE						= "104983";				// 红包
	public static final String	BTN_RED_PACKAGE_OPEN					= "104993";				// 拆红包
	public static final String	TIP_SEND_RED_PACKAGE					= "104998";				// 发了一个{0}
	public static final String	TIP_RED_PACKAGE_NO_MONEY				= "104978";				// 手慢了，红包已经被抢光了
	public static final String	TIP_RED_PACKAGE_DETAIL					= "104975";				// 看看大家的手气
	public static final String	TIP_RED_PACKAGE_FINISH					= "160256";				// 该{0}已过期
	public static final String	MSG_VERSION_NO_SUPPORT					= "105110";				// 当前游戏版本不支持此消息类型
	public static final String	TIP_DRAGON_CHAT							= "132134";				// 巨龙战场中世界频道不可用
	public static final String	INPUT_ALLIANCE_DIALOG					= "134073";				// 我发现了新的宝藏，希望得到大家的帮助，谢谢
	public static final String	CHAT_RESTRICT_TIP						= "132135";				// 需要等级：{0}
	public static final String	POINT_TYPE_NAME_Crystal					= "140082";				// 水晶矿
	public static final String	POINT_TYPE_NAME_Armory					= "140083";				// 军械库
	public static final String	POINT_TYPE_NAME_TrainingField			= "140084";				// 训练场
	public static final String	POINT_TYPE_NAME_MedicalTower			= "140085";				// 医疗大厅
	public static final String	POINT_TYPE_NAME_SupplyPoint				= "140086";				// 补给点
	public static final String	POINT_TYPE_NAME_BessingTower			= "140087";				// 祝福之塔
	public static final String	POINT_TYPE_NAME_TransferPoint			= "140088";				// 传送点
	public static final String	POINT_TYPE_NAME_Barracks				= "140089";				// 骑士大厅
	public static final String	POINT_TYPE_NAME_DragonTower				= "140090";				// 龙塔
	public static final String	POINT_TYPE_NAME_allianceArea			= "115357";				// 联盟堡垒
	public static final String	POINT_TYPE_NAME_tile_banner				= "115534";				// 国旗

	public static final String	TIP_DEF_SUCCESS							= "140219";				// 守卫{0}成功
	public static final String	TIP_DEF_FAILED							= "140220";				// 守卫{0}失败
	public static final String	TIP_ATK_SUCCESS							= "140221";				// 攻击{0}成功
	public static final String	TIP_ATK_FAILED							= "140222";				// 攻击{0}失败
	public static final String	TIP_SHARE_CORDINATE						= "108808";				// 我收藏了一个位置{0}
	public static final String	TIP_ALLIANCE_TREASURE_SHARE				= "102519";				// 我正在挖掘{0}，请协助我开启该宝藏
	public static final String	MENU_ALLIANCE_TREASURE					= "103059";				// 开启

	public static final String	MAIL_TITLE_114000						= "114000";
	public static final String	MAIL_TITLE_114002						= "114002";
	public static final String	MAIL_TITLE_114102						= "114102";
	public static final String	MAIL_TITLE_114006						= "114006";
	public static final String	MAIL_TITLE_114008						= "114008";
	public static final String	MAIL_TITLE_105523						= "105523";
	public static final String	MAIL_TITLE_114014						= "114014";
	public static final String	MAIL_TITLE_114016						= "114016";
	public static final String	MAIL_TITLE_114019						= "114019";
	public static final String	MAIL_TITLE_114020						= "114020";
	public static final String	MAIL_TITLE_114115						= "114115";
	public static final String	MAIL_TITLE_114116						= "114116";
	public static final String	MAIL_TITLE_114117						= "114117";
	public static final String	MAIL_TITLE_114022						= "114022";
	public static final String	MAIL_TITLE_101227						= "101227";
	public static final String	MAIL_TITLE_114124						= "114124";
	public static final String	MAIL_TITLE_114128						= "114128";
	public static final String	MAIL_TITLE_105068						= "105068";
	public static final String	MAIL_TITLE_105069						= "105069";
	public static final String	MAIL_TITLE_113905						= "113905";
	public static final String	MAIL_TITLE_110014						= "110014";
	public static final String	MAIL_TITLE_110100						= "110100";
	public static final String	MAIL_TITLE_110119						= "110119";
	public static final String	MAIL_TITLE_110120						= "110120";
	public static final String	MAIL_TITLE_110121						= "110121";
	public static final String	MAIL_TITLE_105722						= "105722";
	public static final String	MAIL_TITLE_105732						= "105732";
	public static final String	MAIL_TITLE_105742						= "105742";
	public static final String	MAIL_TITLE_111079						= "111079";
	public static final String	MAIL_TITLE_111080						= "111080";
	public static final String	MAIL_TITLE_111066						= "111066";
	public static final String	MAIL_TITLE_114135						= "114135";
	public static final String	MAIL_TITLE_133062						= "133062";
	public static final String	MAIL_TITLE_133026						= "133026";
	public static final String	MAIL_TITLE_133100						= "133100";
	public static final String	MAIL_TITLE_137460						= "137460";
	public static final String	MAIL_TITLE_2910539						= "2910539";
	public static final String	MAIL_TITLE_137461						= "137461";
	public static final String	MAIL_TITLE_133270						= "133270";
	public static final String	MAIL_TITLE_114111						= "114111";
	public static final String	MAIL_TITLE_114025						= "114025";
	public static final String	MAIL_TITLE_115464						= "115464";
	public static final String	MAIL_TITLE_115476						= "115476";
	public static final String	MAIL_TITLE_105714						= "105714";
	public static final String	MAIL_TITLE_105720						= "105720";
	public static final String	MAIL_TITLE_105726						= "105726";
	public static final String	MAIL_TITLE_105727						= "105727";
	public static final String	MAIL_TITLE_105728						= "105728";
	public static final String	MAIL_TITLE_105729						= "105729";
	public static final String	MAIL_TITLE_105730						= "105730";
	public static final String	MAIL_TITLE_3110118						= "3110118";
	public static final String	MAIL_TITLE_103786						= "103786";
	public static final String	MAIL_TITLE_105750						= "105750";
	public static final String	MAIL_TITLE_101019						= "101019";
	public static final String	MAIL_TITLE_110167						= "110167";
	public static final String	MAIL_TITLE_110191						= "110191";
	public static final String	MAIL_TITLE_115335						= "115335";
	public static final String	MAIL_TITLE_114144						= "114144";
	public static final String	MAIL_TITLE_115399						= "115399";
	public static final String	MAIL_TITLE_105757						= "105757";
	public static final String	MAIL_TITLE_105759						= "105759";
	public static final String	MAIL_TITLE_138065						= "138065";
	public static final String	MAIL_TITLE_115429						= "115429";
	public static final String	MAIL_TITLE_138099						= "138099";
	public static final String	MAIL_TITLE_111504						= "111504";
	public static final String	MAIL_TITLE_105567						= "105567";				// 你的资源点被侦查
	public static final String	MAIL_TITLE_114005						= "114005";				// 对方使用了反侦察道具，无法获得侦查信息
	public static final String	MAIL_TITLE_105524						= "105524";				// 被{0}侦查
	public static final String	MAIL_TITLE_137429						= "137429";
	public static final String	MAIL_TITLE_137431						= "137431";
	public static final String	MAIL_TITLE_137430						= "137430";
	public static final String	MAIL_TITLE_103758						= "103758";
	public static final String	MAIL_TITLE_105118						= "105118";
	public static final String	MAIL_TITLE_105117						= "105117";
	public static final String	MAIL_TITLE_111506						= "111506";
	public static final String	MAIL_TITLE_105700						= "105700";
	public static final String	MAIL_TITLE_105704						= "105704";
	public static final String	MAIL_TITLE_105578						= "105578";
	public static final String	MAIL_TITLE_105702						= "105702";
	public static final String	MAIL_TITLE_105706						= "105706";
	public static final String	MAIL_TITLE_108554						= "108554";
	public static final String	MAIL_TITLE_105579						= "105579";
	public static final String	MAIL_TITLE_105019						= "105019";
	public static final String	MAIL_TITLE_115341						= "115341";
	public static final String	MAIL_TITLE_105701						= "105701";
	public static final String	MAIL_TITLE_105705						= "105705";
	public static final String	MAIL_TITLE_105583						= "105583";
	public static final String	MAIL_TITLE_105703						= "105703";
	public static final String	MAIL_TITLE_105581						= "105581";
	public static final String	MAIL_TITLE_105707						= "105707";
	public static final String	MAIL_TITLE_105535						= "105535";
	public static final String	MAIL_TITLE_105582						= "105582";
	public static final String	MAIL_TITLE_105580						= "105580";
	public static final String	MAIL_TITLE_133083						= "133083";
	public static final String	MAIL_TITLE_115493						= "115493";
	public static final String	MAIL_TITLE_115494						= "115494";
	public static final String	MAIL_TITLE_115496						= "115496";
	public static final String	MAIL_TITLE_103715						= "103715";
	public static final String	MAIL_TITLE_108896						= "108896";
	public static final String	MAIL_TITLE_105305						= "105305";
	public static final String	MAIL_TITLE_105335						= "115335";
	public static final String	MAIL_TITLE_115544						= "115544";				// 国旗被摧毁通知
	public static final String	MAIL_TITLE_105771						= "105771";				// 头像上传成功
	public static final String	MAIL_TITLE_101041						= "101041";
	public static final String	MAIL_TITLE_101042						= "101042";
	public static final String	MAIL_TITLE_103691						= "103691";
	public static final String	MAIL_TITLE_132111						= "132111";
	public static final String	MAIL_TITLE_140183						= "140183";
	public static final String	MAIL_TITLE_140181						= "140181";
	public static final String	MAIL_TITLE_110081						= "110081";
	public static final String	MAIL_TITLE_110172						= "110172";
	public static final String	MAIL_TITLE_137451						= "137451";
	public static final String	MAIL_TITLE_2910538						= "2910538";

	public static final String	PERMISSION_INFO_WRITE_SD_CARD			= "132133";				// SD卡权限说明，申请前弹出
	public static final String	PERMISSION_EXPLAIN_WRITE_SD_CARD		= "2100013";			// 解释为什么需要SD卡权限，权限申请被拒绝后弹出
	public static final String	PERMISSION_MANUAL_WRITE_SD_CARD			= "132497";				// 权限申请被拒绝且选择不再询问，提示可以去设置修改
	// public static final String PERMISSION_REQUEST_RECORD_VOICE = "132147";
	// public static final String PERMISSION_REQUEST_RECORD_VIDEO = "132170";
	public static final String	PERMISSION_REQUEST_PNP_TO_ALBUM			= "132185";
	public static final String	PERMISSION_REQUEST_PNP_TO_ALBUM2		= "132188";
	public static final String	PERMISSION_BTN_REQUEST_NOW				= "2100010";			// 现在授权
	public static final String	PERMISSION_BTN_REQUEST_NEXT_TIME		= "2100011";			// 下次再说

	public static final String	PERMISSION_INFO_RECORD_VOICE			= "2100014";
	public static final String	PERMISSION_EXPLAIN_RECORD_VOICE			= "2100015";
	public static final String	PERMISSION_MANUAL_RECORD_VOICE			= "2100016";

	public static final String	PERMISSION_INFO_ALLIANCE_SHARE			= "2100017";
	public static final String	PERMISSION_EXPLAIN_ALLIANCE_SHARE		= "2100018";
	public static final String	PERMISSION_MANUAL_ALLIANCE_SHARE		= "2100019";

	public static final String	PERMISSION_INFO_NEARBY					= "2100020";
	public static final String	PERMISSION_EXPLAIN_NEARBY				= "132435";				// 该功能需要使用您的地理位置，向您推荐附近的人。\n位置信息30分钟后即失效，我们不会存储您的位置，您不必为隐私问题担忧。\n\n是否允许使用您的位置？
	public static final String	PERMISSION_MANUAL_NEARBY				= "2100022";

	public static final String	WEB_SOCKET_AUTHORISING					= "132348";				// 认证中...
	public static final String	WEB_SOCKET_CONNECTING					= "132137";				// 正在连接聊天服务器
	public static final String	WEB_SOCKET_GET_SERVERLIST				= "132138";				// 获取服务器列表
	public static final String	WEB_SOCKET_GET_SERVERLIST_ERROR			= "132139";				// 服务器列表获取错误
	public static final String	WEB_SOCKET_RECONNECTING					= "132140";				// 正在重新连接
	public static final String	WEB_SOCKET_CONNECT_FAIL					= "132141";				// 连接失败，{0}秒后重连
	public static final String	ANOTHER_LOGIN							= "105283";				// 你已在另外一台设备上登录此账号！
	public static final String	ALLIANCE_SHARE							= "115875";				// 联盟分享
	public static final String	ALLIANCE_SHARE_HINT						= "115886";				// 这一刻的想法

	public static final String	AUDIO_SLIDE_TO_CANCEL					= "132142";				// 滑动来取消/SLIDE
																								// TO
																								// CANCEL

	public static final String	BTN_TAKE_PHOTO							= "115878";				// 拍照
	public static final String	BTN_UPLOAD_PHOTO						= "115879";				// 从手机相册选择
	public static final String	TIP_NEW_ALLIANCE_SHARE					= "115884";				// {0}条新消息
	public static final String	DETAIL									= "115885";				// 详情
	public static final String	BTN_LOVE								= "115888";				// 赞
	public static final String	BTN_ABORT_LOVE							= "132177";				// 取消点赞
	public static final String	BTN_COMMENT								= "115889";				// 评论
	public static final String	BTN_DELETE								= "115890";				// 删除
	public static final String	BTN_REPLY								= "115891";				// 回复
	public static final String	BTN_SAVE_IMAGE							= "115892";				// 保存到相册
	public static final String	TIP_SAVE_FAILED							= "115893";				// 保存失败
	public static final String	TIP_SAVE_SUCCESS						= "115894";				// 保存成功
	public static final String	TIP_DELETE								= "115898";				// 确认要删除这条分享吗？
	public static final String	TIP_DELETE_COMMENT						= "132178";				// 确定要删除这条评论吗？
	public static final String	MENU_SWITCH_TO_RECEIVER					= "132171";				// 听筒播放
	public static final String	MENU_SWITCH_TO_SPEAKER					= "132172";				// 扬声器播放
	public static final String	TIP_PLAY_BY_RECEIVER					= "132173";				// 当前为听筒播放模式
	public static final String	TIP_PLAY_BY_SPEAKER						= "132174";				// 当前为扬声器播放模式
	public static final String	TIP_ALLIANCE_HELP						= "102528";				// 我的城堡正在遭受敌人的进攻，请求大家的援助
	public static final String	MENU_ALLIANCE_HELP						= "102530";				// 援助
	public static final String	TIP_ALLIANCE_TREASURE_DISABLE			= "102531";				// 当前战场无法挖掘宝藏;
	public static final String	TIP_DETETCT_DISABLE						= "132175";				// {0}使用了反侦察道具，无法获得侦查信息
	public static final String	TIP_NO_ALLIANCE_SHARE					= "115787";				// 暂无联盟分享消息，赶快点击右上角的图标发送第一条联盟分享吧！
	public static final String	TIP_NO_UNREAD_MAIL						= "132176";				// 您没有未读邮件
	public static final String	TEXT_NAME								= "140047";				// 名称
	public static final String	BTN_LEVEL_CHAT_ROOM						= "132180";				// 离开聊天室并删除所有消息
	public static final String	TIP_LEVEL_CHAT_ROOM						= "132181";				// 如果你不愿再收到这个聊天室的信息，你可以通过下面的选项离开聊天室。离开聊天室之后此聊天室将会从你的聊天列表中删除。
	public static final String	TIP_AUDIO_TOO_SHORT						= "132159";				// 说话时间太短
	public static final String	TIP_AUDIO_TOO_LONG						= "132160";				// 说话时间超长
	public static final String	TIP_LUCK_WHEEL							= "111136";				// 我在幸运轮盘中获得了超赞的奖励，快来看看！
	public static final String	TIP_ABORT_EDIT							= "132199";				// 放弃此次编辑？
	public static final String	BTN_TEXT_ABORT							= "132200";				// 放弃
	public static final String	BTN_TEXT_KEEPON							= "132201";				// 继续编辑
	public static final String	CHANNEL_NAME_RECYCLEBIN					= "132202";				// 回收站
	public static final String	TIP_DRAFT								= "132205";				// 草稿
	public static final String	TIP_RECYCLE_CHANNEL						= "132203";				// 您已领取过奖励的邮件会自动进入该回收站，并在30天后删除。
	public static final String	TIP_RECYCLE_TIME						= "132204";				// {0}天后删除
	public static final String	TIP_RECYCLE_TIME_2						= "132232";				// {0}天后删除
	public static final String	BTN_CUSTOM_CHAT							= "132206";				// 自定义
	public static final String	BTN_CUSTOM_CHAT_ADD						= "132207";				// 添加联系人或聊天室
	public static final String	BTN_CUSTOM_CHAT_ADD_TIP					= "132208";				// 将联系人或者聊天室添加至此自定义频道中，可快速联系他们
	public static final String	CUSTOM_ADD_USER_TIP						= "132209";				// 点击下方头像可快速添加自定义联系人或聊天室。
	public static final String	TITLE_MY_FRIEND							= "132210";				// 我的联系人
	public static final String	TITLE_MY_CHATROOM						= "132211";				// 我的聊天室
	public static final String	TIP_ALLIANCE_SKILL						= "102528";				// 我的城堡正在遭受敌人的进攻，请求大家的援助
	public static final String	TIP_ALLIANCE_TREASURE_WARN				= "132216";				// 城堡10级以上才能开启
	public static final String	TIP_NULL_FRIEND							= "132217";				// 您还没有最近联系人
	public static final String	TIP_NULL_CHATROOM						= "132218";				// 您还没有最近聊天室
	public static final String	CUSTOM_ADD_USER_TIP2					= "132215";				// 点击头像可移除当前联系人或者聊天室(移除不会删掉该聊天对象)\n勾选下方头像可更换聊天对象
	public static final String	MENU_REWARD_ALL							= "132222";				// 全部领奖
	public static final String	CUSTOM_CHAT_ADD_TIP						= "132223";				// 您还没有最近联系人或聊天室。\n跟其他领主沟通交流后，可将最重要的联系人或聊天室添加至此，方便下次快速联络到他们。
	public static final String	TITLE_REPORT							= "105568";				// 报告
	public static final String	TIP_AUDIO_USE							= "132224";				// 按住麦克风即可发送语音
	public static final String	TIP_AUDIO								= "132156";				// 语音
	public static final String	BTN_BATTLE_FIELD_ADD_TIP				= "132227";				// 您还未加入战场，去传送门看看是否有想要参加的活动
	public static final String	BTN_GO_TO_SEE							= "118006";				// 去看看
	public static final String	BATTLE_FIELD_ANCIENT					= "138000";				// 远古战场
	public static final String	BATTLE_FIELD_DRAGON						= "132229";				// 巨龙战场
	public static final String	BATTLE_FIELD_KINGDOM					= "132228";				// 王国远征战场
	public static final String	TIP_GOUNTRY								= "132225";				// 本国
	public static final String	TIP_MOVE_TO_TRASH						= "132231";				// 为了防止邮箱里的邮件越积越多，您已领取过奖励的邮件会被自动放入回收站并在30天后删除，这期间您还可以去回收站看到它。
	public static final String	TITILE_ORIGINAL_COUNTRY					= "132230";				// {0}#{1}
	public static final String	TIP_STEAL_FAILED						= "146391";				// {0}因偷窃银币被我判决为叛国者，请各位领主前往{1}讨伐叛国者!
	public static final String	TIP_SHOT								= "164174";				// 我向坐标{0}发射了{1}。
	public static final String	TIP_TRANSLATING							= "132237";				// 翻译中...
	public static final String	MAIL_TITLE_164182						= "164182";				// 城堡被轰炸通知
	public static final String	MAIL_TITLE_164542						= "164542";				// 大炮轰炸报告
	public static final String	MENU_CLEAR								= "132247";				// 清空
	public static final String	BTN_TEXT_KNOW							= "101189";				// 我知道了
	public static final String	BTN_TEXT_GOTO_SETTING					= "132132";				// 前往设置
	public static final String	TIP_TRANSLATE_SETTING					= "132246";				// 领主大人，我们已为您开启自动翻译，系统会自动将您选择的语言翻译为您的源语言。您可以在“设置-语言”中修改它们。
	public static final String	MSG_ALLIANCE_JOIN						= "115188";				// 我来了，希望能和大家成为朋友，一起打造属于我们的帝国。
	public static final String	TIP_SHOT_2								= "164278";				// 我向坐标{0}发射了{1},轰炸玩家为{2}
	public static final String	BANNER_TITLE							= "164278";				// 我向坐标{0}发射了{1},轰炸玩家为{2}
	public static final String	BANNER_BUY								= "101236";				// 立即购买
	public static final String	BANNER_GOLD								= "107010";				// {0}金币
	public static final String	MENU_BUY_MSG_BG							= "132279";				// 购买同款气泡
	public static final String	BTN_LOCAL_CHATROOM						= "132280";				// {0}聊天室
	public static final String	BTN_GLOBAL_CHATROOM						= "132281";				// 全球聊天室
	public static final String	TITLE_RANDOM_CAHTROOM					= "132282";				// 随机聊天室
	public static final String	BTN_SET_LOCAL_CHATROOM					= "132283";				// 进入{0}聊天室
	public static final String	TIP_SET_LOCAL_CHATROOM					= "132284";				// 点击进入该聊天室，系统将随机为您自动分配{0}玩家。
	public static final String	BTN_SET_GLOBAL_CHATROOM					= "132285";				// 进入全球聊天室
	public static final String	TIP_SET_GLOBAL_CHATROOM					= "132286";				// 点击进入该聊天室，系统将随机为您自动分配全球玩家。
	public static final String	TIP_RANDOM_ROOM_JOINING					= "132293";				// 正在分配房间，请等待
	public static final String	TIP_RANDOM_ROOM_JOIN_FAILED				= "132294";				// 分配房间失败，请稍候重试
	public static final String	TIP_SYS_MSG_NULL						= "132295";				// 当前没有系统消息
	public static final String	TIP_RANDOM_DESTORY						= "132296";				// 聊天室里太久没人说话，已经自动解散了。/n领主大人看看其他聊天室吧！
	public static final String	TIP_SHARE_LINK							= "132297";				// {0}:分享了一个链接
	public static final String	TIP_ATT_SUCSESS							= "115277";				// 我攻击了{0} 战斗胜利
	public static final String	TIP_ATT_FAILED							= "115278";				// 我攻击了{0} 战斗失败
	public static final String	TIP_ATTED_SUCCESS						= "115279";				// 我受到了{0}的攻击 战斗胜利
	public static final String	TIP_ATTED_FAILED						= "115280";				// 我受到了{0}的攻击 战斗失败
	public static final String	TIP_ATT_DRAW							= "115283";				// 我攻击了{0} 战斗平局
	public static final String	TIP_ATTED_DRAW							= "115284";				// 我受到了{0}的攻击 战斗平局
	public static final String	TIP_RANDOM_CHAT_SETTING_TIP				= "132369";				// 领主大人，自定义聊天里新增了随机聊天室功能喔，您可以进入本地聊天室和全球聊天室。在“管理自定义聊天”里添加它们吧。
	public static final String	TIP_CHAT_ERROR_CODE_105201				= "132372";				// 你已被禁言，{0}后可以发言
	public static final String	LINK_CHAT_ERROR_CODE_105201				= "132374";				// 点此联系客服投诉
	public static final String	TIP_CHAT_ERROR_CODE_114104				= "114104";				// 你已被对方屏蔽，无法通信
	public static final String	TIP_CHAT_ERROR_CODE_E100195				= "132375";				// 请给自己起一个名字再发言
	public static final String	LINK_CHAT_ERROR_CODE_E100195			= "132376";				// 去起名
	public static final String	TIP_CHAT_ERROR_CODE_E100196				= "132377";				// 你需要先升级到{0}级才能发言
	public static final String	MENU_VIEW_KING							= "132389";				// 查看国王
	public static final String	MENU_VIEW_CANNON						= "132431";				// 查看大炮
	public static final String	MENU_VIEW_RANKING_LIST					= "132392";				// 查看排行榜
	public static final String	MENU_VIEW_ACTIVITY						= "132397";				// 查看活动
	public static final String	TITLE_CHALLENGE_SUCESS					= "169120";				// 挑战成功
	public static final String	TITLE_CHALLENGE_FAILED					= "169121";				// 挑战失败
	public static final String	TITLE_NEARBY_DISTANCE					= "132436";				// 距你{0}km
	public static final String	TITLE_NEARBY_LAST_LOGIN_TIME			= "132437";				// 上次登录时间：{0}
	public static final String	TITLE_NEARBY							= "132439";				// 附近的人
	public static final String	BTN_YES									= "132459";				// 查看附近的人
	public static final String	BTN_NO									= "132113";				// 拒绝
	public static final String	TIP_NEARBY_NO_BODY						= "132438";				// 您所在的地方太特别了，附近居然一个玩家都没有
	public static final String	TITLE_NEARBY_DISTANCE_M					= "132446";				// 距你{0}m
	public static final String	TIP_OPEN_LOCATION						= "132460";				// 您未开启定位功能，我们无法获取您的位置信息。\n请到手机的系统设置->隐私->定位服务中开启定位，并允许列王的纷争使用定位服务。
	public static final String	BTN_OPEN_LOCATION						= "132186";				// 去设置
	public static final String	TIP_SEARCH_NEARBY_USER					= "132449";				// 正在为您搜索附近的人...
	public static final String	BTN_CLEAR_LOCATION						= "132451";				// 清除位置信息并退出
	public static final String	TIP_CLEAR_LOCATION						= "132453";				// 清除位置信息后，您将不会被附近的人搜索到，确定清除并退出么？
	public static final String	TITLE_NEARBY_MSG						= "132452";				// 附近的消息
	public static final String	NAME_ALL_USER							= "132452";				// 所有人
	public static final String	TIP_AT_ME								= "132456";				// 被@的消息
	public static final String	DRAGON_OBSERVER_CHAT_ROOM				= "132475";				// 巨龙观战聊天室
	public static final String	DRAGON_OBSERVER_JOIN_TIP				= "132476";				// 正在加入巨龙观战者聊天室...
	public static final String	DRAGON_OBSERVER_JOIN_FAILED_TIP			= "132478";				// 抱歉，加入房间失败，请重新加入。
	public static final String	DRAGON_OBSERVER_JOIN_TIP_BTN			= "132479";				// 再次加入
	public static final String	NEARBY_LIKE_NUM_TEXT					= "132489";				// 您今天的点赞次数：{0}
	public static final String	NEARBY_LIKE_TEXT						= "132477";				// 我觉得你很棒，赞一个！回赞我喔！
	public static final String	BTN_DOWNLOAD							= "132444";				// 去下载
	public static final String	BTN_SUBSCRIBE							= "9400581";			// 订阅
	public static final String	TITLE_EXEPRESSION						= "132495";				// 表情
	public static final String	BTN_SUBSCRIBE_CANCEL					= "132498";				// 取消订阅
	public static final String	BTN_BUYED								= "169108";				// 已购买

	public static final String	TITLE_REALTIME_VOICE					= "2100023";			// 实时语音
	public static final String	TITLE_VOICE_SETTING						= "2100024";			// 语音设置
	public static final String	TIP_SPEAKING							= "2100025";			// {0}正在说话
	public static final String	TIP_VOICE_ROOM_ENTER					= "2100026";			// {0}加入了聊天
	public static final String	TIP_VOICE_ROOM_LEAVE					= "132405";				// {0}离开房间
	public static final String	TITLE_VOICE_CHAT_ROOM					= "2100027";			// 语音聊天室
	public static final String	TITLE_SPEAKER							= "2100028";			// 发言者
	public static final String	TITLE_LISTENER							= "2100029";			// 收听者
	public static final String	TITLE_MY_SETTING						= "2100030";			// 我的设置
	public static final String	BTN_PRESS_TO_SPEAK						= "2100031";			// 按住发言
	public static final String	BTN_SAVE_SETTING						= "2100032";			// 保存设置
	public static final String	BTN_JOIN_ROOM							= "2100036";			// 加入语音
	public static final String	TIP_REALTIME_ROOM_JOIN_ERROR			= "2100034";			// 服务器正忙，请稍后再试
	public static final String	TIP_NO_SPEAKER							= "2100037";			// 未设置发言者，盟主及R4可以设置谁可以发言
	public static final String	TIP_NO_LISTENER							= "2100038";			// 一个收听者都没有...
	public static final String	BTN_QUIT_REALTIME_VOICE					= "2100033";			// 退出语音聊天
	public static final String	TIP_RED_PACKAGE_HANDLEDISABLE			= "E100177";			// 未达到领取条件
	public static final String	TIP_ALLIANCE_ALL_MAIL					= "105589";
	public static final String	USER_MAIL_ERROR_TIP						= "105509";				//您输入的收件人不存在！
	public static final String	TIP_RED_PACKAGE_EnvelopesCastleLevel	= "9440083";			//您的城堡等级未达到{0}级，不可领取红包奖励
	public static final String  TITLE_INVITE                            = "132500";            //邀请
	public static final String  TITLE_DEFAULT                           = "default";            //默认加载中
	public static final String  TIP_CHAT_ERROR_CODE_132501              = "132501";            // 您已经不在当前聊天室，无法发送消息
}
